GET http://127.0.0.1:3001/students/student-validar-notas/20

###

POST http://127.0.0.1:3001/students/student
Content-Type: application/json

{
  "userCode": "S001",
  "nombre": "Juan Pérez",
  "notas": [8, 9, "abc"]
}

###

DELETE http://127.0.0.1:3001/students/student/1

###

PUT http://127.0.0.1:3001/students/upload-grades
Content-Type: application/json

{
  "id": "1",
  "notas": [8, 9, 10]
}

###

GET http://127.0.0.1:3001/students/promedio-total